apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory
  namespace: default
data:
  inventory: |
    [all:vars]
    ansible_ssh_user=core
    ansible_become=false
    timeout=60
    ocpappsdomain=apps.ocp43-offline.sales.lab.tlv.redhat.com
    openshift_console_api=apps.ocp43-offline.sales.lab.tlv.redhat.com
    localregistry="docker.io/nginx:latest"
    testproject=sanity-test
    storageclass=thin
    etcdSkip=True
    ocpversion=4

    [masters]
    control-plane-0.ocp43-offline.sales.lab.tlv.redhat.com
    control-plane-1.ocp43-offline.sales.lab.tlv.redhat.com
    control-plane-2.ocp43-offline.sales.lab.tlv.redhat.com

    [etcd:children]
    masters

    [nodes]
    control-plane-0.ocp43-offline.sales.lab.tlv.redhat.com
    control-plane-1.ocp43-offline.sales.lab.tlv.redhat.com
    control-plane-2.ocp43-offline.sales.lab.tlv.redhat.com
    compute-0.ocp43-offline.sales.lab.tlv.redhat.com
    compute-1.ocp43-offline.sales.lab.tlv.redhat.com
    compute-2.ocp43-offline.sales.lab.tlv.redhat.com
    [nodes:children]
    masters

