apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sanity
  namespace: default
spec:
  schedule: " */2 * * * *"
  #schedule: "0 0 * * 0" once a week
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sanity-wrap
            image: quay.io/ypery/ocpsanity:v1.5
            imagePullPolicy: Always
            env:
            - name: KUBECONFIG
              value: "/root/kubeconfig"
            - name:  K8S_AUTH_KUBECONFIG
              value: "/root/kubeconfig"
            command: ["/usr/bin/ansible-playbook"]
            args: ["-i", "/root/inventory", "/root/playbooks/iperf.yaml"]
            volumeMounts:
            - mountPath: /root/inventory
              name: inventory
              subPath: inventory
            - mountPath: /root/kubeconfig
              name: kubeconfig
              subPath: kubeconfig
          volumes:
          - configMap:
              defaultMode: 0777
              name: inventory
            name: inventory
          - configMap:
              defaultMode: 0777
              name: kubeconfig
            name: kubeconfig
          restartPolicy: OnFailure
