apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thin
  namespace: sanitytest
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
          storage: 1Gi
  storageClassName: thin
