apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-storage-claim
  namespace: yaronocps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
          storage: 1Gi
  storageClassName: glusterfs-storage
