apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx
  namespace: sanitytest
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None

