apiVersion: batch/v1
kind: Job
metadata:
  name: sanity
spec:
parallelism: 1
completions: 1
activeDeadlineSeconds: 1800
backoffLimit: 6
template:
    metadata:
      name: pi
    spec:
      containers:
      - name: sanity
        #image: registry.redhat.io/openshift3/ose-ansible
        command: /root/ocpstest/playbooks./sanity_4.sh
      restartPolicy: OnFailure
